//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bloq.stringi", typeof(stringi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blok decyzyjny.
        /// </summary>
        internal static string BLOK_DECYZYJNY {
            get {
                return ResourceManager.GetString("BLOK_DECYZYJNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blok operacyjny.
        /// </summary>
        internal static string BLOK_OPERACYJNY {
            get {
                return ResourceManager.GetString("BLOK_OPERACYJNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemat posiada już jeden blok startowy.
        /// </summary>
        internal static string JestBlokStartowy {
            get {
                return ResourceManager.GetString("JestBlokStartowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy Schemat.
        /// </summary>
        internal static string NowySchmat {
            get {
                return ResourceManager.GetString("NowySchmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerokość:.
        /// </summary>
        internal static string szerokosc {
            get {
                return ResourceManager.GetString("szerokosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysokość:.
        /// </summary>
        internal static string wysokosc {
            get {
                return ResourceManager.GetString("wysokosc", resourceCulture);
            }
        }
    }
}
